import '../providers/language_provider.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _s = {
    'ur': {
      'app_title': 'چوہدری ٹریڈرز',
      'inventory_title': 'اسٹاک انوینٹری',
      'security_subtitle': 'ایپ استعمال کرنے کے لیے PIN یا فنگر پرنٹ اسکین کریں',
      'biometric_reason': 'چوہدری ٹریڈرز کھولنے کے لیے فنگر پرنٹ اسکین کریں',
      'invalid_pin': 'غلط PIN! دوبارہ کوشش کریں',
      'verify_button': 'تصدیق کریں',
      'change_pin': 'PIN تبدیل کریں',
      'old_pin': 'پرانا PIN',
      'new_pin': 'نیا PIN',
      'confirm_pin': 'نئے PIN کی تصدیق',
      'pin_changed': 'PIN کامیابی سے تبدیل ہو گئی',
      'pin_mismatch': 'نیا PIN اور تصدیق ایک جیسی نہیں',
      'pin_min_length': 'PIN کم از کم 4 ہندسے کی ہونی چاہیے',
      'dashboard': 'ڈیش بورڈ',
      'products': 'پروڈکٹس',
      'customers': 'کسٹمرز',
      'sales': 'فروخت',
      'purchases': 'خریداری',
      'collections': 'وصولیاں',
      'expenses': 'اخراجات',
      'cash_book': 'کیش بک',
      'reports': 'رپورٹس',
      'settings': 'سیٹنگز',
      'new_sale': 'نئی فروخت',
      'new_entry': 'نئی انٹری',
      'today_history': 'آج کی فروخت',
      'today_sales': 'آج کی فروخت',
      'today_collections': 'آج کی وصولی',
      'total_receivable': 'کل واجب الادا',
      'stock_value': 'اسٹاک ویلیو',
      'recent_sales': 'حالیہ فروخت',
      'low_stock': 'کم اسٹاک الرٹس',
      'no_sales': 'کوئی فروخت نہیں ملی',
      'stock_ok': 'تمام پروڈکٹس کا اسٹاک ٹھیک ہے',
      'select_customer': 'کسٹمر منتخب کریں',
      'select_product': 'پروڈکٹ',
      'save_sale': 'فروخت محفوظ کریں',
      'sale_saved': 'فروخت محفوظ کر لی گئی ہے',
      'total': 'کل رقم',
      'payment_type': 'ادائیگی کی قسم',
      'cash': 'نقد',
      'credit': 'ادھار',
      'business_info': 'کاروباری معلومات',
      'business_name': 'کاروبار کا نام',
      'owner_name': 'مالک کا نام',
      'save': 'محفوظ کریں',
      'settings_saved': 'سیٹنگز محفوظ ہو گئیں',
      'language': 'زبان',
      'version': 'ورژن',
      'add_expense': 'نیا خرچ',
      'category': 'قسم',
      'amount': 'رقم',
      'description': 'تفصیل',
      'cancel': 'کینسل',
      'no_expenses': 'کوئی اخراجات نہیں',
      'total_expenses': 'کل اخراجات',
      'new_collection': 'نئی وصولی',
      'total_collection': 'کل وصولی',
      'no_collections': 'کوئی وصولی نہیں',
      'new_purchase': 'نئی خریداری',
      'no_purchases': 'کوئی خریداری نہیں',
      'supplier': 'سپلائر',
      'qty': 'مقدار',
      'cost_price': 'قیمت',
      'current_balance': 'موجودہ بیلنس',
      'no_entries': 'کوئی اندراج نہیں',
      'new_entry_cash': 'نیا اندراج',
      'opening_balance': 'افتتاحی بیلنس',
      'cash_in': 'آمد',
      'cash_out': 'خرچ',
      'balance': 'بیلنس',
      'note': 'نوٹ',
      'total_sales': 'کل فروخت',
      'total_purchases': 'کل خریداری',
      'profit': 'منافع (تخمینی)',
      'total_customers': 'کل کسٹمرز',
      'total_products': 'کل پروڈکٹس',
      'unknown': 'نامعلوم',
      'error': 'خرابی',
      'refresh': 'تازہ کریں',
      'payment_method': 'ادائیگی طریقہ',
      'delete': 'حذف کریں',
      'search': 'تلاش کریں',
      'no_products': 'کوئی پروڈکٹ نہیں ملی',
      'add_first_product': 'پہلی پروڈکٹ شامل کریں',
      'search_products': 'پروڈکٹ تلاش کریں',
      'add_product': 'نئی پروڈکٹ شامل کریں',
      'product_name': 'نام (Name)',
      'brand': 'برانڈ (Brand)',
      'purchase_price': 'خرید قیمت (Purchase Price)',
      'sale_price': 'فروخت قیمت (Sale Price)',
      'current_stock': 'موجودہ اسٹاک (Current Stock)',
      'min_stock_level': 'کم از کم اسٹاک (Min Stock)',
      'product_saved': 'پروڈکٹ محفوظ کر لی گئی',
      'edit_product': 'پروڈکٹ ترمیم کریں',
      'product_updated': 'پروڈکٹ اپڈیٹ ہو گئی',
      'product_deleted': 'پروڈکٹ حذف کر دی گئی',
      'stock': 'اسٹاک',
    },
    'en': {
      'app_title': 'Chaudhary Traders',
      'inventory_title': 'Snack Inventory',
      'security_subtitle': 'Enter PIN or scan fingerprint to continue',
      'biometric_reason': 'Scan fingerprint to open Chaudhary Traders',
      'invalid_pin': 'Invalid PIN! Please try again',
      'verify_button': 'Verify',
      'change_pin': 'Change PIN',
      'old_pin': 'Old PIN',
      'new_pin': 'New PIN',
      'confirm_pin': 'Confirm New PIN',
      'pin_changed': 'PIN changed successfully',
      'pin_mismatch': 'New PIN and confirmation do not match',
      'pin_min_length': 'PIN must be at least 4 digits',
      'dashboard': 'Dashboard',
      'products': 'Products',
      'customers': 'Customers',
      'sales': 'Sales',
      'purchases': 'Purchases',
      'collections': 'Collections',
      'expenses': 'Expenses',
      'cash_book': 'Cash Book',
      'reports': 'Reports',
      'settings': 'Settings',
      'new_sale': 'New Sale',
      'new_entry': 'New Entry',
      'today_history': "Today's Sales",
      'today_sales': 'Today Sales',
      'today_collections': 'Today Collections',
      'total_receivable': 'Total Receivable',
      'stock_value': 'Stock Value',
      'recent_sales': 'Recent Sales',
      'low_stock': 'Low Stock Alerts',
      'no_sales': 'No sales found',
      'stock_ok': 'All products stock is fine',
      'select_customer': 'Select Customer',
      'select_product': 'Product',
      'save_sale': 'Save Sale',
      'sale_saved': 'Sale saved successfully',
      'total': 'Total Amount',
      'payment_type': 'Payment Type',
      'cash': 'Cash',
      'credit': 'Credit',
      'business_info': 'Business Information',
      'business_name': 'Business Name',
      'owner_name': 'Owner Name',
      'save': 'Save',
      'settings_saved': 'Settings saved successfully',
      'language': 'Language',
      'version': 'Version',
      'add_expense': 'Add Expense',
      'category': 'Category',
      'amount': 'Amount',
      'description': 'Description',
      'cancel': 'Cancel',
      'no_expenses': 'No expenses found',
      'total_expenses': 'Total Expenses',
      'new_collection': 'New Collection',
      'total_collection': 'Total Collection',
      'no_collections': 'No collections found',
      'new_purchase': 'New Purchase',
      'no_purchases': 'No purchases found',
      'supplier': 'Supplier',
      'qty': 'Quantity',
      'cost_price': 'Cost Price',
      'current_balance': 'Current Balance',
      'no_entries': 'No entries found',
      'new_entry_cash': 'New Entry',
      'opening_balance': 'Opening Balance',
      'cash_in': 'Cash In',
      'cash_out': 'Cash Out',
      'balance': 'Balance',
      'note': 'Note',
      'total_sales': 'Total Sales',
      'total_purchases': 'Total Purchases',
      'profit': 'Profit (Estimated)',
      'total_customers': 'Total Customers',
      'total_products': 'Total Products',
      'unknown': 'Unknown',
      'error': 'Error',
      'refresh': 'Refresh',
      'payment_method': 'Payment Method',
      'delete': 'Delete',
      'search': 'Search',
      'no_products': 'No products found',
      'add_first_product': 'Add First Product',
      'search_products': 'Search products...',
      'add_product': 'Add New Product',
      'product_name': 'Name',
      'brand': 'Brand',
      'purchase_price': 'Purchase Price',
      'sale_price': 'Sale Price',
      'current_stock': 'Current Stock',
      'min_stock_level': 'Min Stock Level',
      'product_saved': 'Product saved successfully',
      'edit_product': 'Edit Product',
      'product_updated': 'Product updated successfully',
      'product_deleted': 'Product deleted',
      'stock': 'Stock',
    },
  };

  static String getText(AppLanguage lang, String key) {
    final langKey = lang == AppLanguage.english ? 'en' : 'ur';
    return _s[langKey]?[key] ?? _s['ur']?[key] ?? key;
  }
}
