// Urdu section ('ur') mein add karo:
'no_products': 'کوئی پروڈکٹ نہیں ملی',
'add_first_product': 'پہلی پروڈکٹ شامل کریں',
'search': 'تلاش کریں',
'search_products': 'پروڈکٹ تلاش کریں',
'add_product': 'نئی پروڈکٹ شامل کریں',
'product_name': 'نام (Name)',
'brand': 'برانڈ (Brand)',
'purchase_price': 'خرید قیمت (Purchase Price)',
'sale_price': 'فروخت قیمت (Sale Price)',
'current_stock': 'موجودہ اسٹاک (Current Stock)',
'min_stock_level': 'کم از کم اسٹاک (Min Stock)',
'product_saved': 'پروڈکٹ محفوظ کر لی گئی',
'edit_product': 'پروڈکٹ ترمیم کریں',
'product_updated': 'پروڈکٹ اپڈیٹ ہو گئی',
'product_deleted': 'پروڈکٹ حذف کر دی گئی',
'delete': 'حذف کریں',
'stock': 'اسٹاک',

// English section ('en') mein add karo:
'no_products': 'No products found',
'add_first_product': 'Add First Product',
'search': 'Search',
'search_products': 'Search products...',
'add_product': 'Add New Product',
'product_name': 'Name',
'brand': 'Brand',
'purchase_price': 'Purchase Price',
'sale_price': 'Sale Price',
'current_stock': 'Current Stock',
'min_stock_level': 'Min Stock Level',
'product_saved': 'Product saved successfully',
'edit_product': 'Edit Product',
'product_updated': 'Product updated successfully',
'product_deleted': 'Product deleted',
'delete': 'Delete',
'stock': 'Stock',
